### ISSUE TITLE
Can't use workflows to generate a single DLL

### ISSUE THREAD

**Issue by molsonkiko** [molsonkiko/JSON-Tools#2]
I would like to make this project into a single downloadable DLL that people can use without having .NET installed on their computer, or at least a downloadable DLL that prompts the user to install the required dependencies when they download the project.
Right now it seems that I can't do that via GitHub Actions, I think because of dependency hell having to do with a .NET 6.0 vs. MSBuild version 16.11 issue.
I've tried experimenting with a bunch of different ways to rewrite the workflows file, but I don't really know what I'm doing so I need some help.

I do believe that this project could be useful to people but at present it won't do anything unless you have Visual Studio. Somewhere down the line I'd also like to make a Notepad++ plugin, but that's an even uglier can of worms that I'm not nearly ready for.

@BdR76, I've looked to [CSVLint](https://github.com/BdR76/CSVLint) as a source of inspiration when developing this project, and you seemed to be able to do what I'm trying to do. Do you think you could help? If you don't have the time, do you have any idea who else might be able to help?

**Comment by BdR76** [comment]
So you want to create a stand-alone DLL, but it's not a plugin? I don't quite understand, how will other users use that DLL?

Anyway, when you created this as a new project in Visual Studio, which template did you choose? The "Class Library (Universal Windows)" or "Class Library (.NET Framework)"? Because the .NET Framework template gives you a dropdownlist option to choose the .NET Framework 2.0, 3.0 up to newer versions. I suspect the other template will just take the most recent version, in this case .NET Core 6.0, which can cause compatibility issues if it's not installed on other PC's.

If I understand correctly, the older the .NET Framework version the more likely that it is already comes pre-installed with Windows (see [this page](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)). So the less compatibility issues you get on other PC's, but with generally less functionality as a downside. For example, with any Windows 7 or newer the .NET Framework 3.5 is already installed.

**Comment by BdR76** [comment]
Btw for something like this, I would first develop it as a stand-alone Windows application, just a .EXE with a form, a text memo and buttons (or like you did in a standalone DLL, idk how that works though). And then create the functions and classes to do the JSON processing, to see what works like a test/prototype version.

And then if you want to develop it as a Notepad++ plug-in, first install the [NppPlugin C# Template](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net). It should appear in the New Projects templates dialog, create a new project using that template. Don't change anything at first, just get it to compile and show as a menu item in the plugins menu. Once you get it up and running in VS the debugging while Notepad++ is calling your plugin really works like a charm. So then slowly copy over the classes and forms you created in your test/prototype project. But that's just my two cents.

**Comment by molsonkiko** [comment]
Thanks for the tips, BdR76! Sorry if I'm having a hard time explaining myself; I'm used to working with late-version Python 3 and barely having to worry about multiple *minor* versions and out-of-support nonsense, much less multiple *major* versions. Your tip about changing to an older version of .NET framework that is pre-installed on Windows is very useful, and I will keep that in mind in the future.

Basically my thought was that this is a fully functional stand-alone app as is, and I was hoping that I could just package it as a single executable that people could just install and work with whether or not they use Notepad++. That's *one* of the reasons that I haven't tried to port all of this into the [Notepad++ plugin pack](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net) demo template. The *other* reason I haven't moved over to the plugin pack yet is that I was unable to get it to compile on my computer but I wanted to build something anyway.
